package com.qrcodedemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.qrcodedemo.beans.GoodsBean;

import com.qrcodedemo.greendao.GoodsBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsBeanDaoConfig;

    private final GoodsBeanDao goodsBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsBeanDaoConfig = daoConfigMap.get(GoodsBeanDao.class).clone();
        goodsBeanDaoConfig.initIdentityScope(type);

        goodsBeanDao = new GoodsBeanDao(goodsBeanDaoConfig, this);

        registerDao(GoodsBean.class, goodsBeanDao);
    }
    
    public void clear() {
        goodsBeanDaoConfig.getIdentityScope().clear();
    }

    public GoodsBeanDao getGoodsBeanDao() {
        return goodsBeanDao;
    }

}
